require_relative '../config/environment.rb'

chicken_soup = Recipe.new("Chicken Soup")
grilled_steak = Recipe.new("Grilled Steak")
tomato_soup = Recipe.new("Tomato Soup")
pot_pie = Recipe.new("Chicken Pot Pie")

onion = Ingredient.new("Onion")
carrot = Ingredient.new("Carrot")
chicken = Ingredient.new("Chicken")
steak = Ingredient.new("Steak")
tomato = Ingredient.new("Tomato")
chicken_broth = Ingredient.new("Chicken Broth")
potato = Ingredient.new("Potato")
broccoli = Ingredient.new("Broccoli")

brandon = User.new("Brandon")
wendy = User.new("Wendy")
robert = User.new("Robert")

recipe_card1 = RecipeCard.new(brandon, chicken_soup, "4/1/2020", 4)
recipe_card2 = RecipeCard.new(wendy, chicken_soup, "2/3/2020", 4.5)
recipe_card3 = RecipeCard.new(robert, chicken_soup, "2/3/2020", 1)
recipe_card4 = RecipeCard.new(brandon, grilled_steak, "2/18/2019", 5)
recipe_card5 = RecipeCard.new(wendy, grilled_steak, "4/4/2019", 1.5)
recipe_card6 = RecipeCard.new(robert, grilled_steak, "4/23/2019", 4.5)
recipe_card7 = RecipeCard.new(brandon, tomato_soup, "6/28/2019", 1)
recipe_card8 = RecipeCard.new(wendy, tomato_soup, "6/31/2019", 3)
recipe_card9 = RecipeCard.new(robert, tomato_soup, "6/2/2019", 3)
recipe_card10 = RecipeCard.new(brandon, pot_pie, "4/2/2020", 4)
recipe_card11 = RecipeCard.new(wendy, pot_pie, "1/24/2020", 4)
recipe_card12 = RecipeCard.new(robert, pot_pie, "2/8/2019", 3.5)

recipe_ingredient1 = RecipeIngredient.new(onion, chicken_soup)
recipe_ingredient2 = RecipeIngredient.new(carrot, chicken_soup)
recipe_ingredient3 = RecipeIngredient.new(chicken, chicken_soup)
recipe_ingredient4 = RecipeIngredient.new(chicken_broth, chicken_soup)
recipe_ingredient5 = RecipeIngredient.new(steak, grilled_steak)
recipe_ingredient6 = RecipeIngredient.new(onion, grilled_steak)
recipe_ingredient7 = RecipeIngredient.new(tomato, tomato_soup)
recipe_ingredient8 = RecipeIngredient.new(onion, pot_pie)
recipe_ingredient9 = RecipeIngredient.new(carrot, pot_pie)
recipe_ingredient8 = RecipeIngredient.new(chicken, pot_pie)

allergy1 = Allergy.new(wendy, steak)
allergy2 = Allergy.new(brandon, tomato)
allergy3 = Allergy.new(robert, onion)
allergy4 = Allergy.new(robert, steak)
allergy5 = Allergy.new(brandon, onion)
allergy6 = Allergy.new(wendy, onion)

binding.pry